import type { Listing, User, Seller } from './types';

export const listings: Listing[] = [
  {
    id: '1',
    userId: 'user_seller_01',
    status: 'live',
    vertical: 'Clinic',
    location_area: 'Central',
    headline: 'Profitable Dental Clinic in Prime Central Location',
    createdAt: '2024-01-15T10:30:00Z',
    updatedAt: '2024-09-01T14:20:00Z',
    teaser: 'Well-established dental practice with a loyal patient base. Fully equipped with modern technology. Strong revenue and consistent profitability.',
    revenue_t12m: 1200000,
    profit_t12m: 450000,
    revenue_last_month: 105000,
    profit_last_month: 38000,
    asking_price: 1800000,
    asking_price_reasoning: 'Valuation based on 4.0x of T12M profit, consistent with industry standards for established dental practices with a strong patient base and modern equipment. Includes goodwill and all assets.',
    assets_summary: 'Includes 3 fully-equipped dental chairs, X-ray machine, and sterilization equipment.',
    licences_summary: 'All necessary MOH licenses are up to date.',
    teamSize: 5,
    established: '2015-06-15T00:00:00.000Z',
    hoursPerWeek: 40,
    market: 'Healthcare Services',
    lease_summary: 'Favorable lease terms with 3 years remaining and option to renew.',
    verified: true,
  },
  {
    id: '2',
    userId: 'user_seller_02',
    status: 'live',
    vertical: 'Tuition',
    location_area: 'East',
    headline: 'Leading Maths & Science Tuition Centre in the East',
    createdAt: '2024-02-20T09:15:00Z',
    updatedAt: '2024-08-28T11:45:00Z',
    teaser: 'Reputable centre with a proven curriculum and a team of experienced tutors. High enrollment rates and waiting lists for popular classes.',
    revenue_t12m: 800000,
    profit_t12m: 300000,
    revenue_last_month: 68000,
    profit_last_month: 25000,
    asking_price: 1000000,
    asking_price_reasoning: 'Priced at approximately 3.3x T12M profit. The valuation reflects the center\'s strong brand reputation, high student retention, and proprietary curriculum which commands premium pricing.',
    assets_summary: 'Classroom furniture for 5 rooms, teaching resources, and proprietary curriculum materials.',
    licences_summary: 'MOE registration and all fire safety certificates are in order.',
    teamSize: 8,
    established: '2018-03-10T00:00:00.000Z',
    hoursPerWeek: 35,
    market: 'Education',
    lease_summary: 'Located in a popular mall with high foot traffic. 2 years left on lease.',
    verified: true,
  },
  {
    id: '3',
    userId: 'user_seller_03',
    status: 'live',
    vertical: 'Retail',
    location_area: 'West',
    headline: 'Boutique Fashion Store with Strong Online Presence',
    createdAt: '2024-03-10T14:20:00Z',
    updatedAt: '2024-07-15T16:30:00Z',
    teaser: 'Trendy boutique in a bustling neighborhood, complemented by a high-traffic e-commerce site. Curated collection of independent labels.',
    revenue_t12m: 650000,
    profit_t12m: 150000,
    revenue_last_month: 55000,
    profit_last_month: 12000,
    asking_price: 400000,
    asking_price_reasoning: 'Valuation includes all stock, store fittings, and the established e-commerce platform. Priced attractively to account for the competitive retail landscape, representing a 2.7x profit multiple.',
    assets_summary: 'Includes all inventory, store fittings, POS system, and e-commerce platform.',
    licences_summary: 'Standard retail and business licenses.',
    teamSize: 3,
    established: '2020-11-22T00:00:00.000Z',
    hoursPerWeek: 45,
    market: 'Fashion Retail',
    lease_summary: 'Affordable rent with 1 year remaining. Landlord open to renewal.',
    verified: false,
  },
  {
    id: '4',
    userId: 'user_seller_04',
    status: 'live',
    vertical: 'F&B',
    location_area: 'North',
    headline: 'Cozy Cafe with Excellent Reviews in a Residential Area',
    teaser: 'A beloved neighborhood cafe known for its specialty coffee and pastries. Strong community following and high ratings on Google and social media.',
    revenue_t12m: 480000,
    profit_t12m: 120000,
    revenue_last_month: 40000,
    profit_last_month: 10000,
    asking_price: 350000,
    asking_price_reasoning: 'Priced at just under 3x profit, which is standard for a well-reviewed F&B establishment with a loyal customer base. The price includes all high-quality equipment and brand assets.',
    assets_summary: 'Full set of professional kitchen equipment, La Marzocco espresso machine, and custom furniture.',
    licences_summary: 'SFA Food Stall License, Public Entertainment License.',
    teamSize: 6,
    established: '2019-05-18T00:00:00.000Z',
    hoursPerWeek: 50,
    market: 'Specialty Coffee & Cafe',
    lease_summary: '2 years remaining on a shophouse lease with no major rent increases planned.',
    verified: true,
  },
    {
    id: '5',
    userId: 'user_seller_02',
    status: 'live',
    vertical: 'Manufacturing',
    location_area: 'Islandwide',
    headline: 'Precision Engineering Firm with MNC Contracts',
    teaser: 'ISO-certified firm specializing in high-tolerance components for the aerospace and medical industries. Long-term contracts with major MNCs.',
    revenue_t12m: 3500000,
    profit_t12m: 800000,
    revenue_last_month: 290000,
    profit_last_month: 65000,
    asking_price: 4000000,
    asking_price_reasoning: 'The 5.0x profit multiple is justified by long-term, sticky contracts with multinational corporations, ISO certification, and significant investment in high-end CNC machinery.',
    assets_summary: 'Fleet of 15 CNC machines, quality control lab, and associated software licenses.',
    licences_summary: 'ISO 9001:2015 certification, BizSAFE Star.',
    teamSize: 22,
    established: '2012-08-05T00:00:00.000Z',
    hoursPerWeek: 45,
    market: 'Precision Engineering',
    lease_summary: 'Owns a 30-year JTC leasehold property with 18 years remaining.',
    verified: true,
  },
  {
    id: '6',
    userId: 'user_seller_03',
    status: 'under_offer',
    vertical: 'Legal',
    location_area: 'Central',
    headline: 'Boutique Law Firm Specializing in Corporate Law',
    teaser: 'Well-respected boutique firm with a stable of SME clients. Focus on M&A, and corporate advisory. Currently under offer.',
    revenue_t12m: 950000,
    profit_t12m: 550000,
    revenue_last_month: 80000,
    profit_last_month: 45000,
    asking_price: 2200000,
    asking_price_reasoning: 'A 4.0x profit multiple reflects the firm\'s strong reputation, recurring client revenue, and specialization in the high-demand corporate law sector. The price includes the handover of all client relationships.',
    assets_summary: 'Office furniture, IT infrastructure, and extensive legal library/subscriptions.',
    licences_summary: 'Singapore Law Practice license.',
    teamSize: 6,
    established: '2016-02-14T00:00:00.000Z',
    hoursPerWeek: 40,
    market: 'Legal Services',
    lease_summary: 'Prestigious office address in the CBD. Lease expires in 18 months.',
    verified: true,
  },
];

const testUsers: { buyer: User; seller1: User; seller2: User; seller3: User } = {
  buyer: {
    id: 'user_buyer_01',
    fullName: 'John Doe',
    email: 'john.doe@example.com',
    avatarUrl: 'https://picsum.photos/seed/buyer/100',
    isVerifiedBuyer: false,
  },
  seller1: {
    id: 'user_seller_01',
    fullName: 'Sarah Johnson',
    email: 'sarah@example.com',
    avatarUrl: 'https://randomuser.me/api/portraits/women/44.jpg',
    isVerifiedBuyer: false,
  },
  seller2: {
    id: 'user_seller_02',
    fullName: 'Michael Chen',
    email: 'michael@example.com',
    avatarUrl: 'https://randomuser.me/api/portraits/men/32.jpg',
    isVerifiedBuyer: false,
  },
  seller3: {
    id: 'user_seller_03',
    fullName: 'Priya Patel',
    email: 'priya@example.com',
    avatarUrl: 'https://randomuser.me/api/portraits/women/68.jpg',
    isVerifiedBuyer: false,
  },
};

const testSellers: Seller[] = [
  {
    id: 'seller_01',
    userId: 'user_seller_01',
    listingIds: ['1', '2'],
  },
];

export const keyHighlights = {
  totalListings: listings.length,
  activeListings: listings.filter(listing => listing.status === 'live').length,
  totalAskingPrice: listings.reduce((sum, listing) => sum + listing.asking_price, 0),
  categories: [...new Set(listings.map(listing => listing.vertical))],
  topPerforming: {
    highestRevenue: Math.max(...listings.map(l => l.revenue_t12m)),
    highestProfitMargin: Math.max(...listings.map(l => (l.profit_t12m / l.revenue_t12m) * 100)),
    mostStaffed: Math.max(...listings.map(l => l.teamSize)),
  },
  verifiedListings: listings.filter(listing => listing.verified).length,
  underOffer: listings.filter(listing => listing.status === 'under_offer').length,
};

export const mockData = {
  listings,
  testUsers,
  testSellers,
  keyHighlights,
};
