import type { Listing } from '@/lib/types';

export const exampleListings: Listing[] = [
  {
    id: 'listing-1',
    vertical: 'E-commerce',
    verified: true,
    status: 'live',
    headline: 'Premium Skincare Dropshipping Store',
    teaser: 'High-margin skincare store with 45% profit margins and 12,000+ monthly visitors. Fully automated with established supplier relationships.',
    location_area: 'Singapore',
    revenue_t12m: 485000,
    profit_t12m: 218250,
    revenue_last_month: 42000,
    profit_last_month: 18900,
    asking_price: 650000,
    asking_price_reasoning: 'Based on 3x annual profit multiple, accounting for growth potential and established supplier relationships.',
    assets_summary: 'Website, social media accounts, supplier contracts, and customer database.',
    licences_summary: 'Business license, resale certificates, and trademark applications in progress.',
    staff_count: 3,
    teamSize: 3,
    established: '2021-03-15T00:00:00.000Z',
    hoursPerWeek: 30,
    market: 'E-commerce & Beauty',
    lease_summary: 'Fully remote operation, no physical lease.',
  },
  {
    id: 'listing-2',
    vertical: 'SaaS',
    verified: false,
    status: 'under_offer',
    headline: 'AI-Powered Social Media Scheduler',
    teaser: 'Subscription-based social media management tool with 1,200+ active users and 92% retention rate. MRR growth of 15% MoM.',
    location_area: 'Remote',
    revenue_t12m: 320000,
    profit_t12m: 185000,
    revenue_last_month: 28000,
    profit_last_month: 16200,
    asking_price: 1200000,
    asking_price_reasoning: 'Valuation based on 6.5x ARR, considering the strong MRR growth and high retention rates.',
    assets_summary: 'Source code, domain, API integrations, and customer base.',
    licences_summary: 'Registered business and software copyright.',
    staff_count: 5,
    teamSize: 5,
    established: '2020-08-10T00:00:00.000Z',
    hoursPerWeek: 40,
    market: 'SaaS & Marketing Tools',
    lease_summary: 'Fully remote team, no physical office lease.',
  },
  {
    id: 'listing-3',
    vertical: 'Content',
    verified: true,
    status: 'live',
    headline: 'Tech News & Reviews Blog',
    teaser: 'Established tech blog with 50,000 monthly visitors and strong affiliate marketing revenue. 80% organic traffic with minimal maintenance required.',
    location_area: 'United States',
    revenue_t12m: 98000,
    profit_t12m: 82000,
    revenue_last_month: 8200,
    profit_last_month: 6900,
    asking_price: 245000,
    asking_price_reasoning: 'Valuation at 3x annual profit, accounting for stable traffic and revenue streams.',
    assets_summary: 'Domain, content assets, social media accounts, and email list.',
    licences_summary: 'Registered business and content copyrights.',
    staff_count: 2,
    teamSize: 1,
    established: '2019-11-05T00:00:00.000Z',
    hoursPerWeek: 15,
    market: 'Technology Media',
    lease_summary: 'Home-based business, no commercial lease.',
  },
  {
    id: 'listing-4',
    vertical: 'Mobile App',
    verified: true,
    status: 'live',
    headline: 'Fitness Tracking App',
    teaser: 'Popular fitness app with 50,000+ downloads and premium subscription model. Strong community and 4.8/5 app store rating.',
    location_area: 'Global',
    revenue_t12m: 185000,
    profit_t12m: 125000,
    revenue_last_month: 15400,
    profit_last_month: 10400,
    asking_price: 450000,
    asking_price_reasoning: 'Valuation at 3.6x annual profit, considering the strong app store rating and growth potential in the fitness tech market.',
    assets_summary: 'Mobile app source code, brand assets, and user base.',
    licences_summary: 'Registered business and app store developer account.',
    staff_count: 4,
    teamSize: 2,
    established: '2020-01-20T00:00:00.000Z',
    hoursPerWeek: 25,
    market: 'Mobile Health & Fitness',
    lease_summary: 'Fully remote team, no physical office lease.',
    sellingReason: 'lack_of_time'
  },
  {
    id: 'listing-5',
    vertical: 'E-commerce',
    verified: false,
    status: 'live',
    headline: 'Sustainable Home Goods Store',
    teaser: 'Eco-friendly home products store with strong brand presence and 35% repeat customer rate. Multiple revenue streams including wholesale.',
    location_area: 'Australia',
    revenue_t12m: 275000,
    profit_t12m: 165000,
    revenue_last_month: 22500,
    profit_last_month: 13500,
    asking_price: 495000,
    asking_price_reasoning: 'Valuation at 3x annual profit, accounting for strong brand loyalty and growth in sustainable products market.',
    assets_summary: 'E-commerce website, inventory, supplier contracts, and brand assets.',
    licences_summary: 'Business registration and product certifications.',
    staff_count: 3,
    teamSize: 3,
    established: '2020-09-12T00:00:00.000Z',
    hoursPerWeek: 35,
    market: 'Sustainable Home Goods',
    lease_summary: 'Small warehouse space with 2 years remaining on lease.',
    sellingReason: 'financing'
  },
  {
    id: 'listing-6',
    vertical: 'Service',
    verified: true,
    status: 'live',
    headline: 'Mobile Pet Grooming Service',
    teaser: 'Established mobile pet grooming service with 200+ regular clients and 4.9/5 rating. Strong reputation and growth potential.',
    location_area: 'United Kingdom',
    revenue_t12m: 185000,
    profit_t12m: 112000,
    revenue_last_month: 15400,
    profit_last_month: 9400,
    asking_price: 335000,
    asking_price_reasoning: 'Valuation based on 3x annual profit, including mobile grooming van and established client base.',
    assets_summary: 'Mobile grooming van, equipment, and customer database.',
    licences_summary: 'Business license and pet care certifications.',
    staff_count: 2,
    teamSize: 2,
    established: '2019-05-18T00:00:00.000Z',
    hoursPerWeek: 40,
    market: 'Pet Care Services',
    lease_summary: 'No physical location, operates from home base with mobile service.',
    sellingReason: 'starting_new_venture'
  }
];
